### ISSUE TITLE
incompatibility with plugin usermanager

### ISSUE THREAD

**Issue by kernam** [tschinz/dokuwiki_stars_plugin#1]
Hi,

first of all thanks for your work creating this nice plugin. During testing it, I figured out that it is not really compatible with the plugin usermanager as both use the same varible DOKU_PLUGIN_IMAGES with different pathes. So when logged in I'm not able to see the stars. When not logged in everything works fine. Renaming the variable to DOKU_PLUGIN_IMAGES_STAR2 in syntax.php did the trick for me.

Regards

Achim

**Comment by tschinz** [comment]
Hello kernam, it is done, next time feels free to make a pull request so I don't have to implement it but only test it ;-)

Cheers
