### ISSUE TITLE
Fix register method and handle method's signature

### ISSUE THREAD

**Issue by sag1** [tschinz/dokuwiki_stars_plugin#5]
Hello,

I am using dokuwiki version 2017-02-19 "Frusterick Manners". The stars plugin register method in action.php and handle method in syntax.php are not compatible with Dokuwiki method's signature.  Can you please adopt these signatures?

Here are the errors:
PHP Warning:  Declaration of action_plugin_stars2::register(&$controller) should be compatible with DokuWiki_Action_Plugin::register(Doku_Event_Handler $controller) in /dokuwiki-2017-02-19e-FrusterickManners/lib/plugins/stars2/action.php on line 0

PHP Warning:  Declaration of syntax_plugin_stars2::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/dokuwiki/prod/versions/dokuwiki-2017-02-19e-FrusterickManners/lib/plugins/stars2/syntax.php on line 0

Thanks in advance

**Comment by tschinz** [comment]
Hello sag1,

done in 8506acfc3a2db04e34bc22590bcff81aa8569599 please test it.

Cheers tschinz

**Comment by sag1** [comment]
Hello Tschinz,

Tested, it works.

Thank you
