### ISSUE TITLE
Star sizes

### ISSUE THREAD

**Issue by MvErven** [tschinz/dokuwiki_stars_plugin#6]
Hello,
Could you please give an example or explanation of sizing the stars?

Wanted to add thes in a table. But they're too large.

Thanks in advance.

**Comment by tschinz** [comment]
You can change the size of the Stars in the Settings. Goto Admin => Configuration Settings => Stars 2 => plugin stars2 height

You can add this to your url

http://yourURL?do=admin&page=config#plugin____stars2____plugin_settings_name

Cheers

**Comment by MvErven** [comment]
Sorry for the late reply. Indeed. It works. Case Closed
