### ISSUE TITLE
Breaks with rc2020-06-01 "Hogfather"

### ISSUE THREAD

**Issue by mtkirchner** [tschinz/dokuwiki_stars_plugin#7]
PHP Fatal error:  Declaration of action_plugin_stars2::register(&$controller) must be compatible with dokuwiki\\Extension\\ActionPlugin::register(Doku_Event_Handler $controller) in /lib/plugins/stars2/action.php on line 0

**Comment by tschinz** [comment]
Well the Progin has to be updated becaues of the changes made in the action plugin system in Hogfather. Action Plugin informatin can be found [here](https://www.dokuwiki.org/devel:action_plugins).
Unfortunately I don't use or support the Dokuwiki Plugins is anymore. If there is somebody willing to take it over I'm gald to do so.
If you fix it yourself and send me a pull request, I'm happy to do so also.

The fix should be very minimal.

Thanks for you understanding

**Comment by lepperm** [comment]
Submitted a pull request to resolve: #8 
Thanks!
